[General]
update-url = https://raw.githubusercontent.com/kitashestakov/shadowrocket/refs/heads/main/standard.conf
bypass-system = true
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = true
udp-policy-not-supported-behaviour = DIRECT
block-quic = on
dns-server = 9.9.9.9, 149.112.112.112
dns-direct-system = false
ipv6 = false
prefer-ipv6 = false
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com,*.ru
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32

[Rule]
# LAN
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
DOMAIN-SUFFIX,local,DIRECT

# Facetime
DOMAIN-SUFFIX,facetime.apple.com,PROXY
DOMAIN-SUFFIX,stun.apple.com,PROXY
DOMAIN-SUFFIX,relay.apple.com,PROXY
DOMAIN,gateway.icloud.com,PROXY

# Apple (direct)
DOMAIN,www-cdn.icloud.com.akadns.net,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT
DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
DOMAIN-SUFFIX,apple.co,DIRECT
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,apple.news,DIRECT
DOMAIN-SUFFIX,appstore.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,crashlytics.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,icloud-content.com,DIRECT
DOMAIN-SUFFIX,me.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT

# Personal direct
DOMAIN-SUFFIX,redd.it,DIRECT
DOMAIN-SUFFIX,reddit.com,DIRECT
DOMAIN-SUFFIX,keenetic.io,DIRECT
DOMAIN-SUFFIX,yandex.net,DIRECT
DOMAIN-SUFFIX,yandex-bank.net,DIRECT
DOMAIN-SUFFIX,vk.com,DIRECT
DOMAIN-SUFFIX,vk-portal.net,DIRECT
DOMAIN-SUFFIX,xiaomi.com,DIRECT
DOMAIN-SUFFIX,pushwoosh.com,DIRECT
DOMAIN-SUFFIX,2gis.com,DIRECT
DOMAIN-SUFFIX,yango.com,DIRECT
DOMAIN-SUFFIX,whoosh.bike,DIRECT
DOMAIN-SUFFIX,lime-shop.com,DIRECT
DOMAIN-SUFFIX,yandex.kz,DIRECT
DOMAIN-SUFFIX,twinby.com,DIRECT
DOMAIN-SUFFIX,adjust.com,DIRECT
DOMAIN,cp.cloudflare.com,DIRECT
DOMAIN-SUFFIX,lencr.org,DIRECT
DOMAIN-SUFFIX,letsencrypt.org,DIRECT

# Торренты - блокировка
DOMAIN-SUFFIX,opentrackr.org,REJECT
DOMAIN-SUFFIX,openbittorrent.com,REJECT
DOMAIN-SUFFIX,transmissionbt.com,REJECT
DOMAIN-SUFFIX,aelitis.com,REJECT
DOMAIN-SUFFIX,utorrent.com,REJECT

# Россия по GeoIP
GEOIP,RU,DIRECT

# Всё остальное - через inleen
FINAL,PROXY

[Host]
localhost = 127.0.0.1
